const Users = [
    {
      "id": 1,
      "first_name": "Emiline",
      "last_name": "McClune",
      "email": "emcclune0@xrea.com",
      "company": "Amazon",
      "Industry": "Technology",
      "gender": "Female",
    },
    {
      "id": 2,
      "first_name": "Felix",
      "last_name": "Ingleston",
      "email": "fingleston1@hibu.com",
      "company": "Capital One",
      "Industry": "Finance",
      "gender": "Female",
    },
    {
      "id": 3,
      "first_name": "Travus",
      "last_name": "Bergstram",
      "email": "tbergstram2@pbs.org",
      "company": "Capital One",
      "Industry": "Technology",
      "gender": "Male",
    },
    {
      "id": 4,
      "first_name": "Holly-anne",
      "last_name": "Knighton",
      "email": "hknighton3@booking.com",
      "company": "Netflix",
      "Industry": "Technology",
      "gender": "Female",
    },
    {
      "id": 5,
      "first_name": "Sollie",
      "last_name": "Naulty",
      "email": "snaulty4@hud.gov",
      "company": "Paramount",
      "Industry": "Technology",
      "gender": "Male"
   , },
    {
      "id": 6,
      "first_name": "Annie",
      "last_name": "Cockayme",
      "email": "acockayme5@tuttocitta.it",
      "company": "Amazon",
      "Industry": "Technology",
      "gender": "Female"
   , },
    {
      "id": 7,
      "first_name": "Celinda",
      "last_name": "Sharvill",
      "email": "csharvill6@narod.ru",
      "company": "Amazon",
      "Industry": "Technology",
      "gender": "Male"
   , },
   {
     "id": 8,
     "first_name": "Lamond",
     "last_name": "Ricket",
     "email": "lricket7@washington.edu",
     "company": "Capital One",
      "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 9,
     "first_name": "Florida",
     "last_name": "Licciardiello",
     "email": "flicciardiello8@sina.com.cn",
     "company": "Indeed",
     "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 10,
     "first_name": "Gerianne",
     "last_name": "Jonas",
     "email": "gjonas9@typepad.com",
     "company": "Edward Jones",
     "Industry": "Finance",
     "gender": "Female",
   },
   {
     "id": 11,
     "first_name": "Amy",
     "last_name": "Tarbath",
     "email": "atarbatha@t.co",
      "company": "Indeed",
      "Industry": "Marketing",
     "gender": "Male"
  , },
   {
     "id": 12,
     "first_name": "Jerrilyn",
     "last_name": "Devil",
     "email": "jdevilb@upenn.edu",
     "company": "Google",
      "Industry": "Marketing",
     "gender": "Male"
  , },
   {
     "id": 13,
     "first_name": "Derrik",
     "last_name": "Halvorsen",
     "email": "dhalvorsenc@loc.gov",
     "company": "Bank of America",
      "Industry": "Finance",
     "gender": "Male"
  , },
   {
     "id": 14,
     "first_name": "Kellia",
     "last_name": "Driutti",
     "email": "kdriuttid@skyrock.com",
     "company": "Google",
     "Industry": "Design",
     "gender": "Male"
  , },
   {
     "id": 15,
     "first_name": "Denys",
     "last_name": "Abrams",
     "email": "dabramse@godaddy.com",
     "company": "Amazon",
      "Industry": "Design",
     "gender": "Male"
  , },
   {
     "id": 16,
     "first_name": "Sophie",
     "last_name": "Wadmore",
     "email": "swadmoref@taobao.com",
     "company": "Edward Jones",
      "Industry": "Finance",
     "gender": "Male"
  , },
   {
     "id": 17,
     "first_name": "Ivonne",
     "last_name": "Axby",
     "email": "iaxbyg@paginegialle.it",
     "company": "Fannie Mae",
      "Industry": "Research",
     "gender": "Male"
  , },
   {
     "id": 18,
     "first_name": "Andee",
     "last_name": "Babcock",
     "email": "ababcockh@hubpages.com",
     "company": "Fannie Mae",
      "Industry": "Research",
     "gender": "Female",
   },
   {
     "id": 19,
     "first_name": "Shawn",
     "last_name": "Baxstair",
     "email": "sbaxstairi@artisteer.com",
     "company": "Edward Jones",
      "Industry": "Research",
     "gender": "Female",
   },
   {
     "id": 20,
     "first_name": "Randolph",
     "last_name": "Chowne",
     "email": "rchownej@nymag.com",
     "company": "Indeed",
      "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 21,
     "first_name": "Hayward",
     "last_name": "Emmet",
     "email": "hemmetk@ustream.tv",
     "company": "Fannie Mae",
      "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 22,
     "first_name": "Paule",
     "last_name": "Kleinhausen",
     "email": "pkleinhausenl@bigcartel.com",
     "company": "Capital One",
      "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 23,
     "first_name": "Berton",
     "last_name": "Wingeatt",
     "email": "bwingeattm@taobao.com",
     "company": "Bank of America",
      "Industry": "Finance",
     "gender": "Female",
   },
   {
     "id": 24,
     "first_name": "Ameline",
     "last_name": "Jeanon",
     "email": "ajeanonn@bandcamp.com",
     "company": "Bank of America",
      "Industry": "Marketing",
     "gender": "Female",
   },
   {
     "id": 25,
     "first_name": "Shepperd",
     "last_name": "Oertzen",
     "email": "soertzeno@arstechnica.com",
     "company": "Bank of America",
      "Industry": "Design",
     "gender": "Male"
  , },
   {
     "id": 26,
     "first_name": "Sean",
     "last_name": "Veltmann",
     "email": "sveltmannp@jigsy.com",
     "company": "Google",
      "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 27,
     "first_name": "Julie",
     "last_name": "Pigot",
     "email": "jpigotq@archive.org",
     "company": "Edward Jones",
     "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 28,
     "first_name": "Goldi",
     "last_name": "Tink",
     "email": "gtinkr@tripod.com",
     "company": "Freddie Mac",
     "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 29,
     "first_name": "Jeannie",
     "last_name": "Kennelly",
     "email": "jkennellys@hugedomains.com",
     "company": "Freddie Mac",
     "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 30,
     "first_name": "Josephine",
     "last_name": "Kennefick",
     "email": "jkennefickt@icq.com",
     "company": "Freddie Mac",
     "Industry": "Marketing",
     "gender": "Female",
   },
   {
     "id": 31,
     "first_name": "Elli",
     "last_name": "Pettigrew",
     "email": "epettigrewu@nsw.gov.au",
     "company": "Amazon",
     "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 32,
     "first_name": "Nevins",
     "last_name": "McGlaughn",
     "email": "nmcglaughnv@webnode.com",
     "company": "Capital One",
     "Industry": "Design",
     "gender": "Male"
  , },
   {
     "id": 33,
     "first_name": "Roseann",
     "last_name": "Schwant",
     "email": "rschwantw@bandcamp.com",
     "company": "Freddie Mac",
     "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 34,
     "first_name": "Hunt",
     "last_name": "McGaughay",
     "email": "hmcgaughayx@freewebs.com",
     "company": "Edward Jones",
     "Industry": "Finance",
     "gender": "Polygen,der"
   },
   {
     "id": 35,
     "first_name": "Inger",
     "last_name": "Sussans",
     "email": "isussansy@webnode.com",
     "company": "Indeed",
     "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 36,
     "first_name": "Hobie",
     "last_name": "Rodman",
     "email": "hrodmanz@oakley.com",
     "company": "Intel",
     "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 37,
     "first_name": "Shandra",
     "last_name": "Creighton",
     "email": "screighton10@storify.com",
     "company": "Intel",
     "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 38,
     "first_name": "Poppy",
     "last_name": "Benne",
     "email": "pbenne11@ameblo.jp",
     "company": "Intel",
     "Industry": "Marketing",
     "gender": "Female",
   },
   {
     "id": 39,
     "first_name": "Skelly",
     "last_name": "Critchard",
     "email": "scritchard12@slate.com",
     "company": "Intel",
     "Industry": "Design",
     "gender": "Female",
   },
   {
     "id": 40,
     "first_name": "Rhea",
     "last_name": "Purple",
     "email": "rpurple13@admin.ch",
     "company": "Samsung",
     "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 41,
     "first_name": "Gilberto",
     "last_name": "Tift",
     "email": "gtift14@simplemachines.org",
     "company": "Samsung",
     "Industry": "Technology",
     "gender": "Female",
   },
   {
     "id": 42,
     "first_name": "Celinka",
     "last_name": "Nolleau",
     "email": "cnolleau15@etsy.com",
     "company": "Intel",
     "Industry": "Technology",
     "gender": "Male"
  , },
   {
     "id": 43,
     "first_name": "Sascha",
     "last_name": "McKevitt",
     "email": "smckevitt16@jigsy.com",
     "company": "Samsung",
     "Industry": "Marketing",
     "gender": "Male"
  , },
   {
     "id": 44,
     "first_name": "Blondelle",
     "last_name": "Mussalli",
     "email": "bmussalli17@wiley.com",
     "company": "Intel",
     "Industry": "Research",
     "gender": "Female",
   },
   {
     "id": 45,
     "first_name": "Gal",
     "last_name": "Corkell",
     "email": "gcorkell18@freewebs.com",
     "company": "Samsung",
     "Industry": "Research",
     "gender": "Male"
  , }
];
module.exports = Users;